### ISSUE TITLE
Clarification for Nvidia Drivers?

### ISSUE THREAD

**Issue by Snarkingjay** [USA-RedDragon/jagex-launcher-flatpak#18]
I used the install script so this might not matter, but could I get clarification on

> If you are using the Nvidia proprietary drivers, you will need to install the drivers.

Judging from the text under it, I assume this means the flatpak version of those drivers?  Before I go any further trying to force the use of Nvidia drivers I"d like to make sure I correctly understand what I am doing as right now no matter what I do, the Runescape client will default to mesa or llvmpipe according to the in game renderer and even if the Jagex Launcher appears under nvidia-smi the runescape client does not (although I am not sure if it's suppose to be listed separately appearing in a flatpak)

My apologies for any mistakes I might have made in this or if it's the wrong venue for this entirely.

**Comment by USA-RedDragon** [comment]
Hello,

> Judging from the text under it, I assume this means the flatpak version of those drivers?

Correct

> no matter what I do, the Runescape client will default to mesa or llvmpipe

I'm curious how you validated that, because I'm not sure where one might find that info in-game.

By chance is your system a multi-GPU system? I.e. has an iGPU and another dedicated GPU which in this case is Nvidia? If so, you might try running `flatpak --user override --env="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia" com.jagex.Launcher` to force the render onto the Nvidia GPU when you next run the launcher

**Comment by Snarkingjay** [comment]
In game I used the developer console to confirm it. I am running a
multi-gpu system, but the launcher seems to open up on the nvidia GPU,
however the game itself then seems to launch almost anywhere else. Might
just be a pebkac.

**Comment by USA-RedDragon** [comment]
This behavior sort of matches what I'd expect with a multi-GPU setup.

Did you try setting this by chance? `flatpak --user override --env="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia" com.jagex.Launcher`. Bascially the two variables tell the GL drivers to force the render on nvidia GPU the next time the flatpak is started. I believe that's what would be required for you and other dual-gpu users.

Also just to get my understanding a bit better, which game client are you using? The RS3 and official OSRS clients are ran in Wine/Proton, whereas the HDOS and RuneLite are ran in the Linux-native Java runtime, so the graphics stacks are a bit different.

> Might just be a pebkac.

Nah! If someone had to ask then it's worth me documenting somewhere, I just don't have a dual-gpu system to test with

**Comment by Snarkingjay** [comment]
I did attempt with both of them, I tried using flatseal just so I could
sanity check everything was entered properly and it did still launch the
launcher which would show up under nvidia-smi, but then the game was
defaulting to mesa or if mesa was completely blocked then llvmpipe. Been
chasing setting up a VM with gpu passthrough so I can compare different
clients performance so hopefully I'll have another option altogether.

**Comment by USA-RedDragon** [comment]
Could I get you to run this in the command line and share the output?

```
flatpak run --user com.jagex.Launcher >~/launcher.log 2>&1
```

The above command makes a `launcher.log` in the home directory that should hopefully have more context we can have a look at as far as GL initiation.

**Comment by Snarkingjay** [comment]
I recently did a fresh install of my OS and the flatpak now runs on the
proper card. If I had to hazard a guess, having steam and lutris run
natively and trying several different versions of the rs client in flatpak
and non flatpak form with their own edits to work probably was causing a
conflict somewhere along the way, though I lack the expertise to confirm
that.

**Comment by USA-RedDragon** [comment]
Well glad to hear you got it working at least!

Feel free to reopen this if the same behavior pops up or a new issue if you end up facing any other issues!
