### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by sindreoy** [USA-RedDragon/jagex-launcher-flatpak#19]
There is an error in the flatpak installation procedure under https://github.com/USA-RedDragon/jagex-launcher-flatpak#installing-the-launcher. The first line reads
```sh
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```
but it should read
```sh
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```
The difference is the `--user` flag.

**Comment by USA-RedDragon** [comment]
Thanks for this, I'll make a PR to fix it
