### ISSUE TITLE
Replace _JAVA_OPTIONS

### ISSUE THREAD

**Issue by Adamcake** [USA-RedDragon/jagex-launcher-flatpak#30]
Regarding this script:
```sh
#!/bin/bash
env _JAVA_OPTIONS=-Duser.home=${XDG_DATA_HOME}/hdos /app/jre/bin/java -jar /app/HDOS/HDOS.jar
```
The _JAVA_OPTIONS usage isn't necessary, although you'd be forgiven for not knowing it. To my surprise, HDOS actually *does* have a way to pass options through to the JVM.

https://github.com/threerings/getdown/blob/792f0a1669faf164f999119921e1d71b750145fd/core/src/main/java/com/threerings/getdown/data/Application.java#L1034-L1041

As you can see here, if you set a property beginning with `app.`, it will be passed through without that prefix. So in this case `-Dapp.user.home=...` will be passed through as `-Duser.home=...`. But you also need to set the HOME environment variable as well, because it seems like hdos-launcher is using that instead of the user.home property.

When I set HOME and app.user.home while invoking HDOS on my host machine, HDOS doesn't attempt to save anything to my real home directory.

Incidentally, it's better practice to use `#!/bin/sh` instead of `#!/bin/bash` for portability, since your script doesn't actually use any shell-extension features which would require bash. `/bin/sh` is required to exist on a POSIX-compliant system whereas bash is not.

**Comment by USA-RedDragon** [comment]
Good to know about the HDOS options. I tried it locally and it works so I'll get it in soon.

> Incidentally, it's better practice to use `#!/bin/sh` instead of `#!/bin/bash` for portability, since your script doesn't actually use any shell-extension features which would require bash. `/bin/sh` is required to exist on a POSIX-compliant system whereas bash is not.

Good call-out. Old habits die hard

Thanks!
