### ISSUE TITLE
Error launching HDOS

### ISSUE THREAD

**Issue by toricorn** [USA-RedDragon/jagex-launcher-flatpak#38]
Hi,
Just ran your install process, also for HDOS. Tho when I try to start HDOS, I get this.
I've checked in Flatseal that it's set to have access to the necessary things.
![screenshot-20231226-162316](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/72469664/45aee343-e0c5-4c1e-8478-1849cfc0209a)

**Comment by toricorn** [comment]
Update;
Seems that it might be overwrite related maybe. Gave it a spin in a fresh install of Linux, worked as expected. But what I did encounter during the update process of the Jagex Launcher itself.. once the update download was done, and the update install window pops up, it got stuck on that. Force-closing it broke the launcher app (after ~15mins).
Ended up replacing the Jagex Launcher files from my Windows install to bypass the update.

**Comment by USA-RedDragon** [comment]
Hello,

Sorry to hear about this issue you're facing. 

After a failed HDOS launch, does this file exist in your home directory? If it does, could you share it to this issue?

`~/.var/app/com.jagex.Launcher/data/hdos/hdos/launcher.log`

Failing that, I can send over a command to run HDOS directly from the Flatpak, bypassing the Jagex Launcher so we can make sure it's not some issue with the way the launcher wants to start it. 

I am curious, since this Flatpak _should_ have all the permissions it needs for 99% of systems, what sorts of things are you having to change in Flatseal for this app?

The failed update loop of the launcher sounds like what happened with the previous Jagex Launcher release. Could you run `flatpak list` and confirm the versions of the Jagex-related Flatpaks?

**Comment by toricorn** [comment]
> Hello,
> 
> Sorry to hear about this issue you're facing.
> 
> After a failed HDOS launch, does this file exist in your home directory? If it does, could you share it to this issue?
> 
> `~/.var/app/com.jagex.Launcher/data/hdos/hdos/launcher.log`
> 
> Failing that, I can send over a command to run HDOS directly from the Flatpak, bypassing the Jagex Launcher so we can make sure it's not some issue with the way the launcher wants to start it.
> 
> I am curious, since this Flatpak _should_ have all the permissions it needs for 99% of systems, what sorts of things are you having to change in Flatseal for this app?
> 
> The failed update loop of the launcher sounds like what happened with the previous Jagex Launcher release. Could you run `flatpak list` and confirm the versions of the Jagex-related Flatpaks?

Hi again,

It might just have been an overwrite issue with the existing hdos folder in the home directory.. But when I got HDOS up and running on the other system, the client never created a HDOS folder within the home directory. Everything was in the default directory; `(~/.var/app/com.jagex.Launcher/data/hdos/hdos)`

I just used Flatseal to check for what values was applied to the Jagex Launcher, didn't change anything from your default set values.

![Screenshot_20231226_204042](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/72469664/01cf5876-1dc3-4e98-bfbc-0a23855503b8)
![Screenshot_20231226_210624](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/72469664/f297d068-de80-4276-ac61-8c548575b2d5)
![Screenshot_20231226_204011](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/72469664/c9f5dbe4-cc2d-4bbd-b2ff-e56c23da5714)

**Comment by dotNetCory** [comment]
Hi I think I'm having the same issue as the screenshot above, but here's the details from mine, same error but I hit show details on mine

![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/60733518/29662f9e-7592-43c7-ad81-4cbbfb9d8b5d)


![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/60733518/8bdf81da-b809-4364-9889-22ece752c46c)

**Comment by nmlynch94** [comment]
Seeing a similar issue on my system when installing from scratch (fedora 39, Nvidia). After installation using the script commands from the README, the first launch prompts for a self-update. Upon applying, the update freezes with the progress bar as posted by the prior user. The flatpak is unable to write to the files in the prefix for some reason. The launcher logs are saying they are unable to open files to update. 

```
12/28/2023 16:07:02 DEBUG - Unable to open file [C:\Program Files (x86)\Jagex Launcher\locales\fa.pak][C0010000](5 : 00000005)
12/28/2023 16:07:02 DEBUG - Unable to open file [C:\Program Files (x86)\Jagex Launcher\locales\cs.pak][C0010000](5 : 00000005)
12/28/2023 16:07:02 DEBUG - Unable to open file [C:\Program Files (x86)\Jagex Launcher\locales\el.pak][C0010000](5 : 00000005)
12/28/2023 16:07:02 DEBUG - Workflow.5983f09f - Task.9a661f74.applyUpdate - Repository.db6f7bf1 - Error: Source(5) Index(79) Count(9) Type (3) Code(964) CodeEx(5) Response(4) Retry(5.00)
12/28/2023 16:07:02 DEBUG - Workflow.5983f09f - Task.9a661f74.applyUpdate - Repository.db6f7bf1 - Error: Source(5) Index(77) Count(9) Type (3) Code(964) CodeEx(5) Response(4) Retry(5.00)
12/28/2023 16:07:02 DEBUG - Workflow.5983f09f - Task.9a661f74.applyUpdate - Repository.db6f7bf1 - Error: Source(5) Index(78) Count(9) Type (3) Code(964) CodeEx(5) Response(4) Retry(5.00)
```

**Comment by USA-RedDragon** [comment]
Hey thanks for those logs @nmlynch94 I think I know _exactly_ what's going on now. Will update later tonight when I try to fix this.

**Comment by USA-RedDragon** [comment]
Give this a shot again with the latest update. I reverted the change that was causing the locals update errors and I think I have the launch script set to clean up the files that caused this. Worst case, deleting `~/.var/app/com.jagex.Launcher/data/wine/drive_c/Program Files (x86)/Jagex Launcher/locales` directory after the update should get it working again

**Comment by nmlynch94** [comment]
I can confirm it's working on an installation from scratch now. Not sure about the update issue the original poster mentioned, but it's probably safe to assume it was related.

**Comment by USA-RedDragon** [comment]
Thanks for confirming. I'll leave this issue open for now so other folks can report back

**Comment by toricorn** [comment]
> Thanks for confirming. I'll leave this issue open for now so other folks can report back

Works fine with the latest update :+1:

**Comment by USA-RedDragon** [comment]
Glad to hear!
