### ISSUE TITLE
Runelite Open Screenshot Folder nonfunctional

### ISSUE THREAD

**Issue by joeamansfield** [USA-RedDragon/jagex-launcher-flatpak#43]
When you right click the screenshot button to open screenshot folder in runelite, it does not work.

I'm also unable to manually locate the screenshot folder, so I'm not sure if this is an issue with screenshots in general, or just with the button to open the folder.

**Comment by USA-RedDragon** [comment]
HDOS or RuneLite?

**Comment by joeamansfield** [comment]
Runelite

**Comment by USA-RedDragon** [comment]
Alright, I'll figure out the appropriate way for a Flatpak to save screenshots. In the meantime, screenshots are stored in `/home/YOUR_USERNAME/.var/app/com.jagex.Launcher/.runelite/screenshots`

**Comment by USA-RedDragon** [comment]
The next update to the Flatpak (~30 minutes after the above PR is merged) will move the existing screenshots to `$HOME/Pictures/RuneLite` and future screenshots will be saved there as well.

**Comment by joeamansfield** [comment]
Awesome, thanks!
