### ISSUE TITLE
Jagex Launcher was not able to start

### ISSUE THREAD

**Issue by stortzm** [USA-RedDragon/jagex-launcher-flatpak#50]
This is an issue with (choose one):
- [ ] RS3
- [x] Official Jagex OSRS
- [x] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**
when launching the Jagex Launcher
![Screenshot from 2024-01-27 22-18-32](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/22046129/c39b772f-75c1-4322-81d7-1668dec463a7)
_Unfortunately the Jagex Launcher was not able to start. Please check your connection and try restarting the launcher._
Restarting /Relaunching yields the same message.

**Screenshots**
![Screenshot from 2024-01-27 22-24-12](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/22046129/34463818-8c1c-4217-9d77-836b1fa4f33d)

**System**
 - OS: Ubuntu 20.04.4 LTS
 - GPU Vendor:  NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]

**Comment by USA-RedDragon** [comment]
In the command line could you run the following? This will attempt to launch it and redirect the logs to a file in the current directory called `launcher.log` . Could you share that log?

`flatpak --user run com.jagex.Launcher > launch.log 2>&1`

There's also a Jagex Launcher log at `$HOME/.var/app/com.jagex.Launcher/data/wine/drive_c/users/reddragon/AppData/Local/Jagex Launcher/logs/host.developer.<date>.log`, could you share the one with the latest date?

**Comment by stortzm** [comment]
> In the command line could you run the following? This will attempt to launch it and redirect the logs to a file in the current directory called `launcher.log` . Could you share that log?
> 
> `flatpak --user run com.jagex.Launcher > launch.log 2>&1`
> 
> There's also a Jagex Launcher log at `$HOME/.var/app/com.jagex.Launcher/data/wine/drive_c/users/reddragon/AppData/Local/Jagex Launcher/logs/host.developer.<date>.log`, could you share the one with the latest date?

it turned out to be a long file, so I won't paste the full .log on this comment, but here:
[launch.log](https://github.com/USA-RedDragon/jagex-launcher-flatpak/files/14077259/launch.log)

I should also add that this window shows up before every launch:
![Screenshot from 2024-01-28 15-09-38](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/22046129/a7339642-93a1-4537-b88e-28685279a424)
not sure if it's relevant

`$ wine --version`
`wine-5.0 (Ubuntu 5.0-3ubuntu1)`

**Comment by USA-RedDragon** [comment]
Sorry for the delay, I've had the flu all week and wasn't able to get around to this.

The logs show that Wine isn't able to open an OpenGL context. 

```
0494:err:wgl:X11DRV_WineGL_InitOpenglInfo  couldn't initialize OpenGL, expect problems
0494:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
0494:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 013AFD98.
```

Can you run `flatpak --user list` and share the output? There are some GL-related packages that _might_ be missing. How did you install the Flatpak? 

---

> I should also add that this window shows up before every launch:

The "The wine configuration in /var/data/wine is being updated, please wait..." window _should_ appear on every launch. 

> `$ wine --version`
> `wine-5.0 (Ubuntu 5.0-3ubuntu1)`

Flatpaks don't use the host software, so this is irrelevant. This Flatpak ships with `wine-8.0-2786-g3061bb04122 (Staging)` (until yesterday, when it was updated to `wine-8.0-3001-g39021e609a2 (Staging)`

**Comment by stortzm** [comment]
> Can you run flatpak --user list and share the output?

![Screenshot from 2024-02-13 01-13-09](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/22046129/b2374562-d831-4f54-8242-da7feadb5298)

**Comment by USA-RedDragon** [comment]
Looks like you're missing `org.freedesktop.Platform.GL32.nvidia-525-147-05`, both the 64-bit and 32-bit Nvidia drivers should be installed.

**Comment by stortzm** [comment]
> both the 64-bit and 32-bit Nvidia drivers should be installed.

installing the missing 32bit driver worked
![Screenshot from 2024-02-14 23-16-43](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/22046129/51921896-e878-49e8-86ad-a0561782ce46)

closing issue
