### ISSUE TITLE
[Known Issue] World models unloading/flickering on Runescape 3

### ISSUE THREAD

**Issue by USA-RedDragon** [USA-RedDragon/jagex-launcher-flatpak#58]
Sometimes in RuneScape 3 with Ambient Occlusion enabled, particularly with NVIDIA cards, the walls and floors and other 3d models end up popping out of existence. Moving the camera around causes them to flicker in and out of existence. The current solution to this is to disable Ambient Occlusion in the game settings.

**Comment by USA-RedDragon** [comment]
https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/13051767/0ff2d006-de6d-466b-ace1-127527cc1288

**Comment by Friendliness** [comment]
Thank you so much, for a few weeks my screen turned into something like this
![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/62225953/ae40472a-e6fd-4861-9154-12c834510e44)

I found out it somehow disappears when any player character is previewed, like for example in the equipment tab, by examining someone, opening the wardrobe...

This is the same exact screen but with the equipment tab extended a bit
![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/62225953/90e8656a-8d03-4050-b799-2bf1f5b7bbe6)

It was driving me up the wall but disabling ambient occlusion seems to fix it!

**Comment by USA-RedDragon** [comment]
This is fixed in the latest release
