### ISSUE TITLE
Run the program after installation

### ISSUE THREAD

**Issue by VlaK0r** [USA-RedDragon/jagex-launcher-flatpak#62]
Hello!
Thank you for your hard work!
Please tell me how to run the program after installation?

**Comment by USA-RedDragon** [comment]
Flatpak's place a `.desktop` entry so it appears in your "start menu"/launcher 

![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/13051767/3eed4312-e2cb-4ded-80ba-31806849c6ac)

Otherwise, if you want to run it via command line, `flatpak run com.jagex.Launcher` should do the trick

**Comment by VlaK0r** [comment]
> Flatpak's place a `.desktop` entry so it appears in your "start menu"/launcher

![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/77666575/403bb0b6-0e74-41cf-8be4-336d7a8b24fe)

there is nothing

**Comment by USA-RedDragon** [comment]
How did you install the app? And what distribution are you on?

**Comment by VlaK0r** [comment]
> How did you install the app? And what distribution are you on?

I installed it according to this instruction

`flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --user --if-not-exists JagexLauncher https://jagexlauncher.flatpak.mcswain.dev/JagexLauncher.flatpakrepo
# Required for 32-bit compatibility. Jagex Launcher is 32-bit.
flatpak install --user flathub org.freedesktop.Platform.Compat.i386/x86_64/23.08
flatpak install --user flathub org.freedesktop.Platform.GL32.default/x86_64/23.08
# Install the launcher itself
flatpak install --user JagexLauncher com.jagex.Launcher
# Install RuneLite (if desired)
flatpak install --user JagexLauncher com.jagex.Launcher.ThirdParty.RuneLite
# Install HDOS (if desired)
flatpak install --user JagexLauncher com.jagex.Launcher.ThirdParty.HDOS`

**Comment by VlaK0r** [comment]
> And what distribution are you on?

Debian 12
KDE Plasma

**Comment by VlaK0r** [comment]
Using the command `flatpak run com.jagex.Launcher` The launcher is starting

But after launching the game, there are graphical bugs. 
When running through the Bolt, everything works fine.

**Comment by USA-RedDragon** [comment]
Can you screenshot the graphical issues you're having? By chance do they look like the examples in this issue? https://github.com/USA-RedDragon/jagex-launcher-flatpak/issues/58

**Comment by VlaK0r** [comment]
> Can you screenshot the graphical issues you're having? By chance do they look like the examples in this issue? #58

This setting partially solves the problem with textures, but still the sky and distant objects continue to disappear.
But interestingly, when running through a Bolt, there is no such problem at all. It doesn't matter if the option is enabled or not.

**Comment by VlaK0r** [comment]
> Oh and what GPU vendor are you using?

3060

**Comment by USA-RedDragon** [comment]
> But interestingly, when running through a Bolt, there is no such problem at all

Please don't compare the experience between Bolt and this Flatpak. We take two completely different approaches to the same problem: Bolt uses the Linux-native RS3 NXT client from the Linux-native .deb packages that Jagex publishes, whereas this Flatpak uses Wine/Proton to run the Windows-native launcher and Windows-native RS3/OSRS clients. Running RS3 via Wine/Proton is required to utilize the official Jagex Launcher, which only downloads the Windows-native game clients.

The two experiences will certainly differ, and skyboxes/distant objects popping in and out are an issue that upstream Wine/Proton has yet to fix.

**Comment by VlaK0r** [comment]
> uses Wine/Proton to run the Windows-native launcher and Windows-native RS3/OSRS clients

Does it turn out that in your case everything is uploaded via vine?

**Comment by USA-RedDragon** [comment]
RuneLite and HDOS use their Linux-native counterparts, but the official RS3 and OSRS clients are Wine.

I am looking into the possibility of tricking the Jagex Launcher into using the Linux-native game

**Comment by USA-RedDragon** [comment]
Good news, I got it working. I'm going to test tonight and release it tomorrow
