### ISSUE TITLE
List instructions for how to set RuneLite launcher configuration options

### ISSUE THREAD

**Issue by bepzi** [USA-RedDragon/jagex-launcher-flatpak#65]
In order to develop RuneLite plugins with a Jagex Account, you have to temporarily set `--insecure-write-credentials` as a RuneLite client argument. See https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts

See also https://github.com/runelite/runelite/wiki/RuneLite-Launcher-Configuration for other options one might want to configure.

This means we need to launch RuneLite separately from the Jagex Launcher (and pass `--configure` to `RuneLite.jar`), but how to do that with this Flatpak is unclear and/or doesn't work:

```
pinetree% flatpak --user list
Name                            Application ID                                           Version            Branch                Origin
Jagex Launcher                  com.jagex.Launcher                                       0.32.0             stable                JagexLauncher
RuneLite                        com.jagex.Launcher.ThirdParty.RuneLite                   2.6.13             stable                JagexLauncher
Freedesktop Platform            org.freedesktop.Platform                                 23.08.12           23.08                 flathub
i386                            org.freedesktop.Platform.Compat.i386                                        23.08                 flathub
Mesa                            org.freedesktop.Platform.GL.default                      24.0.1             23.08                 flathub
Mesa (Extra)                    org.freedesktop.Platform.GL.default                      24.0.1             23.08-extra           flathub
nvidia-550-54-14                org.freedesktop.Platform.GL.nvidia-550-54-14                                1.4                   flathub
Mesa                            org.freedesktop.Platform.GL32.default                    24.0.1             23.08                 flathub
nvidia-550-54-14                org.freedesktop.Platform.GL32.nvidia-550-54-14                              1.4                   flathub
openh264                        org.freedesktop.Platform.openh264                        2.1.0              2.2.0                 flathub
Breeze GTK theme                org.gtk.Gtk3theme.Breeze                                 5.27.8             3.22                  flathub

pinetree% flatpak run com.jagex.Launcher.ThirdParty.RuneLite
bwrap: execvp /bin/sh: No such file or directory

pinetree% flatpak run com.jagex.Launcher.ThirdParty.RuneLite --configure
bwrap: execvp /bin/sh: No such file or directory
```

I'm not super familiar with Flatpaks so it's likely I'm doing something wrong -- but either way, it would be good to list instructions in the README for how to do this.

I was able to temporarily work around this by manually editing `~/.local/share/flatpak/runtime/com.jagex.Launcher.ThirdParty.RuneLite/x86_64/stable/active/files/RuneLite.exe` to temporarily add the `--configure` flag; then launching RuneLite through the Jagex Launcher caused the launcher config to appear.

**Comment by USA-RedDragon** [comment]
Good info here, I didn't intend this to be used as part of a development workflow, but I see how it could be useful and I'd like to support that usecase.

Here's what I'm aiming for:

```bash
flatpak run --env=EXTRA_RUNELITE_ARGS="--configure" --user com.jagex.Launcher
```

Then, when you launch RuneLite via the launcher, `EXTRA_RUNELITE_ARGS` gets appended to the launch args in the `RuneLite.exe` script. I've got it working locally, so I'll get a PR up with it in a little bit

**Comment by billbrod** [comment]
Hi! Sorry for resurrecting this old thread, but is it possible to find the `credentials.properties` that gets created when `--insecure-write-credentials` is set? According to the [runelite wiki](https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts), it should get created in the `.runelite` folder, but I'm not sure what the equivalent directory is. Is it possible to find this file?

**Comment by USA-RedDragon** [comment]
Assuming the flatpak is installed as a user flatpak: `~/.var/app/com.jagex.Launcher/.runelite`

**Comment by billbrod** [comment]
Thanks! The folder is there (and looks correct), but I don't see the `credentials.properties` file being created.

The steps I did were:
- run  `flatpak run --env=EXTRA_RUNELITE_ARGS="--configure" --user com.jagex.Launcher`
- start RuneLite through the launcher, set `--insecure-write-credentials`, 
- exit the launcher
- run `flatpak run --user com.jagex.Launcher` to open the launcher
- start RuneLite through the launcher

I'd expect to see the `credentials.properties` being created when I complete the final step -- am I missing something?

**Comment by mbtaylor12** [comment]
Is there a way to have the saved configuration options persist after running: `flatpak run --env=EXTRA_RUNELITE_ARGS="--configure" --user com.jagex.Launcher`?

I am trying to change the scale setting. Using the above launch command, the configuration screen does pop up when clicking play. I set the Scale to "0.5" and click save. I click play to verify the setting saved, and it is still "0.5" as expected. But when I close the Jagex launcher and re-open normally, the setting did not save.

If I launch back into the configure settings, the scale is blank again.

I do see a "settings.json" file which looks like it should be used in `~/.local/share/flatpak/runtime/com.jagex.Launcher.ThirdParty.RuneLite/x86_64/stable/active/files/jre/bin` but changing scale in the file does not reflect when launched, and the configuration launch doesn't seem to be saving there.
