### ISSUE TITLE
RuneLite does not launch.

### ISSUE THREAD

**Issue by nmlynch94** [USA-RedDragon/jagex-launcher-flatpak#69]
This is an issue with (choose one):

- [ ] RS3
- [ ] Official Jagex OSRS
- [x] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**
Unbound variable in the shell script is causing RuneLite not to launch

**To Reproduce**
1. Install Jagex launcher and RuneLite extension from the README
2. Launch RuneLite

**Expected behavior**
RuneLite launches

**Screenshots**
![image](https://github.com/USA-RedDragon/jagex-launcher-flatpak/assets/40608755/ff3cfa8a-fc7d-49c4-a679-a03b56d018e5)

**System**
 - OS: Fedora 39
 - GPU Vendor:  NVIDIA

**Comment by USA-RedDragon** [comment]
Oh, chee. Yeah I see... I'll get it patched. Thanks for letting me know

**Comment by IMRogue** [comment]
don't know if this problem is similar or not https://pastebin.com/xjRfjmqH
